<?php
/**
 * Silver Touch Technologies Limited.
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://www.silvertouch.com/MagentoExtensions/LICENSE.txt
 *
 * @category   Sttl
 * @package    Sttl_Authorizecim
 * @copyright  Copyright (c) 2011 Silver Touch Technologies Limited. (http://www.silvertouch.com/MagentoExtensions)
 * @license    http://www.silvertouch.com/MagentoExtensions/LICENSE.txt
 */ 

?>
<?php $_code=$this->getMethodCode() ?>
<ul class="form-list" id="payment_form_<?php echo $_code ?>" style="display:none;">
	<?php if(Mage::helper('authorizecim')->displayOldCard()): 
		  $cards = $this->getOldCreditCard();
		  if(!empty($cards)):?>
	<li>
        <label for="cim_payment_profileid" ><?php echo $this->__('Use Old Credit Card') ?></label>
        <div class="input-box">
            <select id="cim_payment_profileid" name="payment[cim_payment_profileid]" class="cc-select" onChange="usecreditcard(this.value)">
                <option value=""><?php echo $this->__('--Please Select--')?></option>
            <?php foreach ($cards as $_typeCode => $_typeName): ?>
                <option value="<?php echo $_typeName['value'] ?>"<?php /*if($_typeName['value']==$_ccType): ?> selected="selected"<?php endif*/ ?>><?php echo $_typeName['label'] ?></option>
            <?php endforeach ?>
            </select>
        </div>
    </li>
    <li>&nbsp;
	</li>
    <?php endif; ?>
	<?php endif; ?>
    <li>
    	<ul id="authorizecim_form">
		    <li>
		        <label for="<?php echo $_code ?>_cc_type" class="required"><em>*</em><?php echo $this->__('Credit Card Type') ?></label>
		        <div class="input-box">
		            <select id="<?php echo $_code ?>_cc_type" name="payment[cc_type]" class="required-entry validate-cc-type-select">
		                <option value=""><?php echo $this->__('--Please Select--')?></option>
		            <?php $_ccType = $this->getInfoData('cc_type') ?>
		            <?php foreach ($this->getCcAvailableTypes() as $_typeCode => $_typeName): ?>
		                <option value="<?php echo $_typeCode ?>"<?php /*if($_typeCode==$_ccType): ?> selected="selected"<?php endif*/ ?>><?php echo $_typeName ?></option>
		            <?php endforeach ?>
		            </select>
		        </div>
		    </li>
		    <li>
		        <label for="<?php echo $_code ?>_cc_number" class="required"><em>*</em><?php echo $this->__('Credit Card Number') ?></label>
		        <div class="input-box">
		            <input type="text" id="<?php echo $_code ?>_cc_number" name="payment[cc_number]" title="<?php echo $this->__('Credit Card Number') ?>" class="input-text validate-cc-number validate-cc-type" value="" />
		        </div>
		    </li>
		    <li id="<?php echo $_code ?>_cc_type_exp_div">
		        <label for="<?php echo $_code ?>_expiration" class="required"><em>*</em><?php echo $this->__('Expiration Date') ?></label>
		        <div class="input-box">
		            <div class="v-fix">
		                <select id="<?php echo $_code ?>_expiration" name="payment[cc_exp_month]" class="month validate-cc-exp required-entry">
		                <?php $_ccExpMonth = $this->getInfoData('cc_exp_month') ?>
		                <?php foreach ($this->getCcMonths() as $k=>$v): ?>
		                    <option value="<?php echo $k?$k:'' ?>"<?php /*if($k==$_ccExpMonth): ?> selected="selected"<?php endif*/ ?>><?php echo $v ?></option>
		                <?php endforeach ?>
		                </select>
		            </div>
		            <div class="v-fix">
		                <?php $_ccExpYear = $this->getInfoData('cc_exp_year') ?>
		                <select id="<?php echo $_code ?>_expiration_yr" name="payment[cc_exp_year]" class="year required-entry">
		                <?php foreach ($this->getCcYears() as $k=>$v): ?>
		                    <option value="<?php echo $k?$k:'' ?>"<?php /*if($k==$_ccExpYear): ?> selected="selected"<?php endif*/ ?>><?php echo $v ?></option>
		                <?php endforeach ?>
		                </select>
		            </div>
		        </div>
		    </li>
		    <?php echo $this->getChildHtml() ?>
		    <?php if($this->hasVerification()): ?>
		    <li id="<?php echo $_code ?>_cc_type_cvv_div">
		        <label for="<?php echo $_code ?>_cc_cid" class="required"><em>*</em><?php echo $this->__('Card Verification Number') ?></label>

		        <div class="input-box">
		            <div class="v-fix">
		                <input type="text" title="<?php echo $this->__('Card Verification Number') ?>" class="input-text cvv required-entry validate-cc-cvn" id="<?php echo $_code ?>_cc_cid" name="payment[cc_cid]" value="" />
		            </div>
		            <a href="#" class="cvv-what-is-this"><?php echo $this->__('What is this?') ?></a>
		        </div>
		    </li>
		    <?php endif; ?>
		    <?php if ($this->hasSsCardType()): ?>
		    <li id="<?php echo $_code ?>_cc_type_ss_div">
		        <ul class="inner-form">
		            <li class="form-alt"><label for="<?php echo $_code ?>_cc_issue" class="required"><em>*</em><?php echo $this->__('Switch/Solo/Maestro Only') ?></label></li>
		            <li>
		                <label for="<?php echo $_code ?>_cc_issue"><?php echo $this->__('Issue Number') ?>:</label>
		                <span class="input-box">
		                    <input type="text" title="<?php echo $this->__('Issue Number') ?>" class="input-text validate-cc-ukss cvv" id="<?php echo $_code ?>_cc_issue" name="payment[cc_ss_issue]" value="" />
		                </span>
		            </li>
		            <li>
		                <label for="<?php echo $_code ?>_start_month"><?php echo $this->__('Start Date') ?>:</label>
		                <div class="input-box">
		                    <div class="v-fix">
		                        <select id="<?php echo $_code ?>_start_month" name="payment[cc_ss_start_month]" class="validate-cc-ukss month">
		                        <?php foreach ($this->getCcMonths() as $k=>$v): ?>
		                            <option value="<?php echo $k?$k:'' ?>"<?php if($k==$this->getInfoData('cc_ss_start_month')): ?> selected="selected"<?php endif ?>><?php echo $v ?></option>
		                        <?php endforeach ?>
		                        </select>
		                    </div>
		                    <div class="v-fix">
		                        <select id="<?php echo $_code ?>_start_year" name="payment[cc_ss_start_year]" class="validate-cc-ukss year">
		                        <?php foreach ($this->getSsStartYears() as $k=>$v): ?>
		                            <option value="<?php echo $k?$k:'' ?>"<?php if($k==$this->getInfoData('cc_ss_start_year')): ?> selected="selected"<?php endif ?>><?php echo $v ?></option>
		                        <?php endforeach ?>
		                        </select>
		                    </div>
		                </div>
		            </li>
		            <li class="adv-container">&nbsp;</li>
		        </ul>
    	</ul>
    </li>
            <script type="text/javascript">
        //<![CDATA[
        var SSChecked<?php echo $_code ?> = function() {
            var elm = $('<?php echo $_code ?>_cc_type');
            if (['SS','SM','SO'].indexOf(elm.value) != -1) {
                $('<?php echo $_code ?>_cc_type_ss_div').show();
            } else {
                $('<?php echo $_code ?>_cc_type_ss_div').hide();
            }
        };

        Event.observe($('<?php echo $_code ?>_cc_type'), 'change', SSChecked<?php echo $_code ?>);
        SSChecked<?php echo $_code ?>();
	    //]]>
        </script>
    </li>
    <?php endif; ?>
	<script type="text/javascript">
		usecreditcard = function(value) {

		if (value != "") {
               $('authorizecim_form').hide();
                
              $('<?php echo $_code ?>_cc_type').addClassName('required-entry validate-cc-type-select');
			  $('<?php echo $_code ?>_cc_number').addClassName('validate-cc-number validate-cc-type');
			  $('<?php echo $_code ?>_expiration').addClassName('required-entry');
			  $('<?php echo $_code ?>_expiration_yr').addClassName('required-entry');
            } else {
                
                 $('authorizecim_form').show();
              $('<?php echo $_code ?>_cc_type').removeClassName('required-entry validate-cc-type-select');
			  $('<?php echo $_code ?>_cc_number').removeClassName('validate-cc-number validate-cc-type');
			  $('<?php echo $_code ?>_expiration').removeClassName('required-entry');
			  $('<?php echo $_code ?>_expiration_yr').removeClassName('required-entry');
            }
        };
	</script>
</ul>